### ISSUE TITLE
node-import is broken on the latest node LTS

### ISSUE THREAD

**Issue by hyphmongo** [queueit/KnownUser.V3.Javascript#1]
The `node-import` package depdendency graph includes the `natives` module which is unstable and broken on node version 12. The package has not been updated in over 5 years. 

Is there any example / alternative implementation that does not use this package?

Error when running node:

```
fs.js:27
const { Math, Object } = primordials;

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Repos\app\node_modules\natives\index.js:143:24)
    at Object.<anonymous> (C:\Repos\app\node_modules\node-import\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at Module.require (C:\Repos\app\node_modules\require-in-the-middle\index.js:43:24)
```

running `yarn why natives`

```
[1/4] Why do we have the module "natives"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "natives@1.1.6"
info Reasons this module exists
   - "node-import#fs-extra#graceful-fs" depends on it
   - Hoisted from "node-import#fs-extra#graceful-fs#natives"
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "20KB"
info Disk size with transitive dependencies: "20KB"
info Number of shared dependencies: 0
Done in 1.16s.
```

`node -v`: v12.14.1

**Comment by sarooghi** [comment]
we are going to remove **node-import** dependency in the next version of the sample and rewrite the sample. 
For now, you can simply add 
```
module = module || {};
(exports = (module.exports = QueueIT));
```
at the end of [js SDK file queueit-knownuserv3-sdk.js) ](https://github.com/queueit/KnownUser.V3.Javascript/blob/master/SDK/Javascript/queueit-knownuserv3-sdk.js) and then require the SDK without any need for **'node-import'** module.
It means adding `const QueueIT = require("./sdk/queueit-knownuserv3-sdk.js");`  to the sample file.

**Comment by hyphmongo** [comment]
thanks, this worked for me!
